name: stab-py
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - matplotlib=3.4.*
  - netcdf4
  - nco
  - cdo
  - xarray
  - pandas
  - scipy
  - mpltern
  - ipython 
  - pip:
     - COMSTABPY
